# WAJIB: project ini pakai AndroidX (appcompat, core, swiperefreshlayout)
android.useAndroidX=true

# Jangan bikin BuildConfig kalau gak dipakai (build lebih cepat)
android.defaults.buildfeatures.buildconfig=false

# Memori buat Gradle di GitHub Actions
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
